require("prototypes.custom-events.custom-events")
require("prototypes.custom-inputs")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.shortcuts")
require("prototypes.technology")